---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
  enabled: true
platforms:
  - name: centos-7
    box: centos/7
    privileged: true
    groups:
      - "cluster"

  - name: debian-buster
    box: debian/buster64
    privileged: true
    groups:
      - "cluster"
  # https://blog.centos.org/2020/12/future-is-centos-stream/
  # - name: centos-8
  #   box: centos/8
  #   privileged: true
  #   groups:
  #     - "cluster"

  - name: fedora-35
    box: generic/fedora35
    privileged: true
    groups:
      - "cluster"

  - name: ubuntu-focal
    box: ubuntu/focal64
    privileged: true
    groups:
      - "cluster"

provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: profile_tasks, timer
    ssh_connection:
      pipelining: false
  log: True
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  options:
    sudo: True
  lint:
    name: flake8
